#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 22, 2022 06:52:10 PM CST  platform: Windows NT

import sys
import webbrowser

from pruebas import vp_start_guiStore

try:
    import tkinter as tk
except ImportError:
    import tkinter as tk

from ordenarBuques import vp_start_gui3
from cliente import*
mainUser=""

def openmanual():
    path = 'file:///C:/Users/andre/OneDrive/Escritorio/Manual.pdf'
    webbrowser.open_new(path)

def ingresar(x):
    vp_start_gui3(x)

def vp_start_gui2(x):
    global mainUser
    mainUser=x
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel2 (root)
    root.mainloop()

w = None
def create_Toplevel2(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel2 (w)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel2:
    def __init__(self, top=None):
        
        
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("662x300+293+109")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(background="#ffffff")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Label1 = tk.Label(top)
        self.Label1.place(x=90, y=5, height=35, width=478)
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Verdana} -size 20 -weight bold")
        self.Label1.configure(foreground="#8cc6ff")
        self.Label1.configure(text='''MANEJO DE USUARIOS''')

        self.Button1 = tk.Button(top)
        self.Button1.place(x=550, y=210, height=34, width=87)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#9dceff")
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#ffffff")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Tienda''')
        self.Button1.configure(command=lambda: vp_start_guiStore(mainUser))

        self.Button1_1 = tk.Button(top)
        self.Button1_1.place(x=550, y=170, height=34, width=87)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#00ff80")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1_1.configure(foreground="#ffffff")
        self.Button1_1.configure(highlightbackground="#ffffff")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(relief="flat")
        self.Button1_1.configure(text='''Tablero''')
        self.Button1_1.configure(command=lambda: ingresar(mainUser))

        self.Label2 = tk.Label(top)
        self.Label2.place(x=0, y=54, height=12, width=194)
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''EDITAR USUARIOS''')

      

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(x=30, y=71, height=11, width=84)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#ffffff")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Name:''')

        self.Label2_1_1 = tk.Label(top)
        self.Label2_1_1.place(x=20, y=94, height=11, width=84)
        self.Label2_1_1.configure(activebackground="#f9f9f9")
        self.Label2_1_1.configure(activeforeground="black")
        self.Label2_1_1.configure(background="#ffffff")
        self.Label2_1_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1_1.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2_1_1.configure(foreground="#000000")
        self.Label2_1_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1_1.configure(highlightcolor="black")
        self.Label2_1_1.configure(text='''Password:''')

        self.Label2_1_2 = tk.Label(top)
        self.Label2_1_2.place(x=40, y=119, height=20, width=84)
        self.Label2_1_2.configure(activebackground="#f9f9f9")
        self.Label2_1_2.configure(activeforeground="black")
        self.Label2_1_2.configure(background="#ffffff")
        self.Label2_1_2.configure(disabledforeground="#a3a3a3")
        self.Label2_1_2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2_1_2.configure(foreground="#000000")
        self.Label2_1_2.configure(highlightbackground="#d9d9d9")
        self.Label2_1_2.configure(highlightcolor="black")
        self.Label2_1_2.configure(text='''Age:''')

    

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(x=110, y=71, height=20, width=114)
        self.Entry1.configure(background="white")
        self.Entry1.configure(cursor="fleur")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry1_1 = tk.Entry(top)
        self.Entry1_1.place(x=110, y=94, height=20, width=114)
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(disabledforeground="#a3a3a3")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(foreground="#000000")
        self.Entry1_1.configure(highlightbackground="#d9d9d9")
        self.Entry1_1.configure(highlightcolor="black")
        self.Entry1_1.configure(insertbackground="black")
        self.Entry1_1.configure(selectbackground="blue")
        self.Entry1_1.configure(selectforeground="white")

        self.Entry1_2 = tk.Entry(top)
        self.Entry1_2.place(x=110, y=119, height=20, width=114)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(disabledforeground="#a3a3a3")
        self.Entry1_2.configure(font="TkFixedFont")
        self.Entry1_2.configure(foreground="#000000")
        self.Entry1_2.configure(highlightbackground="#d9d9d9")
        self.Entry1_2.configure(highlightcolor="black")
        self.Entry1_2.configure(insertbackground="black")
        self.Entry1_2.configure(selectbackground="blue")
        self.Entry1_2.configure(selectforeground="white")

        self.Label2_2 = tk.Label(top)
        self.Label2_2.place(x=-10, y=210, height=11, width=194)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#ffffff")
        self.Label2_2.configure(cursor="fleur")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''ELIMINAR USUARIOS''')

        self.Label2_1_3 = tk.Label(top)
        self.Label2_1_3.place(x=30, y=230, height=11, width=84)
        self.Label2_1_3.configure(activebackground="#f9f9f9")
        self.Label2_1_3.configure(activeforeground="black")
        self.Label2_1_3.configure(background="#ffffff")
        self.Label2_1_3.configure(disabledforeground="#a3a3a3")
        self.Label2_1_3.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2_1_3.configure(foreground="#000000")
        self.Label2_1_3.configure(highlightbackground="#d9d9d9")
        self.Label2_1_3.configure(highlightcolor="black")
        self.Label2_1_3.configure(text='''Name:''')

        self.Entry1_3 = tk.Entry(top)
        self.Entry1_3.place(x=110, y=230, height=20, width=114)
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(disabledforeground="#a3a3a3")
        self.Entry1_3.configure(font="TkFixedFont")
        self.Entry1_3.configure(foreground="#000000")
        self.Entry1_3.configure(highlightbackground="#d9d9d9")
        self.Entry1_3.configure(highlightcolor="black")
        self.Entry1_3.configure(insertbackground="black")
        self.Entry1_3.configure(selectbackground="blue")
        self.Entry1_3.configure(selectforeground="white")

        self.Button1_1_1 = tk.Button(top)
        self.Button1_1_1.place(x=250, y=110, height=34, width=87)
        self.Button1_1_1.configure(activebackground="#ececec")
        self.Button1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1.configure(background="#ff8080")
        self.Button1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1_1_1.configure(foreground="#ffffff")
        self.Button1_1_1.configure(highlightbackground="#ffffff")
        self.Button1_1_1.configure(highlightcolor="black")
        self.Button1_1_1.configure(pady="0")
        self.Button1_1_1.configure(relief="flat")
        self.Button1_1_1.configure(text='''Editar''')
        self.Button1_1_1.configure(command=lambda: req_edit(mainUser,self.Entry1.get(),self.Entry1_1.get(),self.Entry1_2.get()) and tk.messagebox.showinfo(message="Editado con exito", title="Atencion"))

        self.Button1_1_1_1 = tk.Button(top)
        self.Button1_1_1_1.place(x=250, y=220, height=34, width=87)
        self.Button1_1_1_1.configure(activebackground="#ececec")
        self.Button1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1.configure(background="#ff8080")
        self.Button1_1_1_1.configure(cursor="fleur")
        self.Button1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1_1_1_1.configure(foreground="#ffffff")
        self.Button1_1_1_1.configure(highlightbackground="#ffffff")
        self.Button1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1.configure(pady="0")
        self.Button1_1_1_1.configure(relief="flat")
        self.Button1_1_1_1.configure(text='''Eliminar''')
        self.Button1_1_1_1.configure(command=lambda:req_erase(self.Entry1_3.get()) and tk.messagebox.showinfo(message="Eliminado con exito", title="Atencion"))

        self.Button1_2 = tk.Button(top)
        self.Button1_2.place(x=500, y=250, height=34, width=137)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#ff80ff")
        self.Button1_2.configure(cursor="fleur")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.Button1_2.configure(foreground="#ffffff")
        self.Button1_2.configure(highlightbackground="#ffffff")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(relief="flat")
        self.Button1_2.configure(text='''Reportes''')
        self.Button1_2.configure(command=lambda: openmanual())



